[Service]
Host = "localhost"
Port = 49992
ConnectRetries = 3
Labels = []
OpenMsg = "device simple started"
MaxResultCount = 50000
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "localhost"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "localhost"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
EnableRemote = false
File = "./device-simple.log"
Level = "DEBUG"

# Pre-define Devices
[[DeviceList]]
  Name = "RandNum-Device-01"
  Profile = "RandNum-Device"
  Description = "Random Number Generator Device"
  Labels = [ "random", "test" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = "random"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Resource = "Random"
    OnChange = false
    Frequency = "8s"

[[DeviceList]]
  Name = "RandInt-Device-01"
  Profile = "RandInt-Device"
  Description = "Random Integer Number Generator Device"
  Labels = [ "random", "test" ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.Other]
      Address = "random-integer"
      Port = "300"
  [[DeviceList.AutoEvents]]
    Resource = "randomInteger"
    OnChange = false
    Frequency = "5s"

 [[DeviceList]]
   Name = "RandBool-Device-01"
   Profile = "RandBool-Device"
   Description = "Random Boolean Value Generator Device"
   Labels = [ "random", "test" ]
   [DeviceList.Protocols]
     [DeviceList.Protocols.Other]
       Address = "random-boolean"
       Port = "300"
   [[DeviceList.AutoEvents]]
     Resource = "randomBoolean"
     OnChange = false
     Frequency = "7s"

  [[DeviceList]]
    Name = "RandFloat-Device-01"
    Profile = "RandFloat-Device"
    Description = "Random Float Value Generator Device"
    Labels = [ "random", "test" ]
    [DeviceList.Protocols]
      [DeviceList.Protocols.Other]
        Address = "random-float"
        Port = "300"
    [[DeviceList.AutoEvents]]
      Resource = "randomFloat"
      OnChange = false
      Frequency = "6s"
  [[DeviceList]]
      Name = "LightSensor-Device-01"
      Profile = "LightSensor-Device"
      Description = "get LightSensor data"
      Labels = [ "light-sensor"]
      [DeviceList.Protocols]
        [DeviceList.Protocols.Other]
          Address = "light-sensor-addr"
          Port = "300"
      [[DeviceList.AutoEvents]]
        Resource = "LightSensorData"
        OnChange = false
        Frequency = "6s"

  [[DeviceList]]
     Name = "Led-Device-01"
     Profile = "Led-Device"
     Description = "LED Device"
     Labels = [ "led" ]
     [DeviceList.Protocols]
       [DeviceList.Protocols.Other]
         Address = "led-sensor-addr"
         Port = "300"
     [[DeviceList.AutoEvents]]
       Resource = "led"
       OnChange = false
       Frequency = "3s"
